### ISSUE TITLE
U+031A COMBINING LEFT ANGLE ABOVE is misplaced

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#421]
Moved from googlei18n/noto-alpha#259. 

Imported from [Google Code issue #259](https://code.google.com/p/noto-alpha/issues/detail?id=259) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T02:34:59.000Z:

----
In Noto Sans and Noto Serif, the character is misplaced. Compare the rendering of the sequences d̚  and g̚  in Noto, Calibri, and DejaVu.

The two examples above can be found in pages ix and 17 of the IPA handbook.

The first is Calibri and the 2nd and the 3rd are Noto Sans and Noto Serif. 

![calibri](https://cloud.githubusercontent.com/assets/12721521/8659749/acd58694-2961-11e5-921f-3ddbe3bab143.png)
![noto-sans](https://cloud.githubusercontent.com/assets/12721521/8659750/ace6da5c-2961-11e5-9297-b868d9f61594.png)
![noto-serif](https://cloud.githubusercontent.com/assets/12721521/8659751/aceb37fa-2961-11e5-95ab-8e6890f4cf0e.png)

**Comment by jungshik** [comment]
@tiroj commented : 
I’m not sure that this is a bug. The positioning of the combining angle mark in the Noto fonts is as
we have it in Brill and Cambria, and I believe the character illustrated on pp. ix and 17 of the IPA 
handbook is the spacing modifier character 02FA, not this combining mark.

**Comment by jungshik** [comment]
Cambria (Win 8), Noto Sans (latest) and Noto Serif (latest). All three fonts position U+031A (above base)  and U+02FA (to the right of the previous character and spacing) in a similar manner. 

The first two use U+031 and the second two use U+02FA.  If the original issue (positioning of U+031A) is WAI(working as intended), I wonder what to about U+02FA.  

![alpha259 cambria](https://cloud.githubusercontent.com/assets/8578343/9098164/ebc1af40-3b7c-11e5-8e72-a003156ef961.png)
![alpha259 noto_sans](https://cloud.githubusercontent.com/assets/8578343/9098162/ebbc6b16-3b7c-11e5-8b13-2b4eacf9ca03.png)
![alpha259 noto_serif](https://cloud.githubusercontent.com/assets/8578343/9098163/ebc08cb4-3b7c-11e5-9ed0-dd3dfc64fca9.png)

**Comment by moyogo** [comment]
This is a bug.
U+02FA MODIFIER LETTER END HIGH TONE was added for UPA in Unicode 4.0 and is not intended to be the “unaudible release” diacritic, U+031A is.

However https://www.internationalphoneticassociation.org/sites/default/files/phonsymbol.pdf notes U+02FA might look better than U+031A. This is probably because U+031A is unusable in most fonts. Although it’s closer to the right thing, I’m thinking we need to fix this in DejaVu fonts, the positioning and advance width delta could be better. Doulos SIL and Charis SIL almost get it right as well but need to add advance width.

U+031A should float on the top right (its combining class is 232 - Above right) very much like U+02FA. In many cases U+031A could change the advance width of the base letter like other top right diacritics.
Furthermore U+031A should sit on the right of the glyph (it should be fine kerning slightly), it should have its horizontal stroke sit at the top at ascender-height.

The “Report on the 1989 Kiel Convention” in *Journal of the International Phonetic Association*, volume 19, issue 1, 1989, describes it as the “postposed diacritic [ ̚]”, and the original proposal in “The Association’s alphabet” in *Journal of the International Phonetic Association*, volume 5, issue 2, 1975, has it in the top right corner with  it’s own advance width.

“The Association’s alphabet” in *Journal of the International Phonetic Association*, volume 5, issue 2, 1975, page 53
![screen shot 2015-09-04 at 16 49 50](https://cloud.githubusercontent.com/assets/1923747/9688091/04084ec8-5325-11e5-94df-63a6b401766c.png)

“The Association’s alphabet” in *Journal of the International Phonetic Association*, volume 6, issue 1, 1976, page 2
![screen shot 2015-09-04 at 16 48 34](https://cloud.githubusercontent.com/assets/1923747/9688077/ec2e8254-5324-11e5-848f-242d6c112a8a.png)

“Report on the 1989 Kiel Convention” in *Journal of the International Phonetic Association*, volume 19, issue 1, 1989, page 71
![screen shot 2015-09-04 at 16 44 50](https://cloud.githubusercontent.com/assets/1923747/9688030/ac68b400-5324-11e5-8067-649c9fc12d9f.png)

I think the way U+031A and U+02FA differ is that U+031A is a corner with bars of the same length (in the original documents) whereas U+02FA has a longer vertical bar (in UPA).
I'm not sure where the U+031A shape with a longer horizontal bar originates from, but it is probably inadequate even though it is widespread.

**Comment by jungshik** [comment]
Noto Sans (p3 built from glyphs source) : 

![bug421 sans_p3](https://cloud.githubusercontent.com/assets/8578343/10703991/9f692c96-7988-11e5-9bba-ae91eaeeee85.png)

@moyogo Thanks for great details. Take a look at the screenshot. The first two use U+031A and the second two uses U+02FA.

**Comment by moyogo** [comment]
@jungshik A more conservative design would have the same visual length for the horizontal and vertical strokes of U+031A, instead of the horizontal one being longer than the vertical one. Both strokes can also be longer, closer to the length of the ascender.

**Comment by marekjez86** [comment]
en test case for fontdiff input
[en-421.html.zip](https://github.com/googlei18n/noto-fonts/files/616461/en-421.html.zip)

sample output for Noto Sans Black (U+031A and  U+02FA now have a consistent design)
![en-421-sans-black](https://cloud.githubusercontent.com/assets/13322623/20671089/b56568b8-b530-11e6-81b8-6c4cf8cb7b2f.jpg)

Testcase outputs
[en-421-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616471/en-421-NotoSans-Black.pdf)
[en-421-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616470/en-421-NotoSans-Italic.pdf)
[en-421-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616472/en-421-NotoSansDisplay-Black.pdf)
[en-421-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616473/en-421-NotoSansDisplay-Italic.pdf)
[en-421-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616475/en-421-NotoSerif-Black.pdf)
[en-421-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616474/en-421-NotoSerif-Italic.pdf)
[en-421-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616476/en-421-NotoSerifDisplay-Black.pdf)
[en-421-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616477/en-421-NotoSerifDisplay-Italic.pdf)

@moyogo : what do you think? are we done here?

**Comment by moyogo** [comment]
@marekjez86 A couple of issues remain. The shape of U+031A is still unconventional (see previous comments, both sides of the corner should have the same length) and I’m not sure the positioning is correct for all plosive consonants. Could you test "p̚t b̚t t̚t d̚t ʈ̚t ɖ̚t c̚t ɟ̚t k̚t ɡ̚t g̚t q̚t ɢ̚t ʡ̚t ʔ̚t m̚t ɱ̚t n̚t ɳ̚t ɲ̚t ŋ̚t ɴ̚t" to confirm the positioning?

**Comment by marekjez86** [comment]
Updated test case for fontdiff
[en-421.html 2.zip](https://github.com/googlei18n/noto-fonts/files/617616/en-421.html.2.zip)

Two samples:
notosans-black
![notosans-black](https://cloud.githubusercontent.com/assets/13322623/20688171/947a8dce-b574-11e6-9b79-b6622d27e787.jpg)
notoserif-italic
![notoserif-italic](https://cloud.githubusercontent.com/assets/13322623/20688179/9e877a84-b574-11e6-9416-fe723dc815bd.jpg)

All sample results:
[en-421-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/617618/en-421-NotoSans-Black.pdf)
[en-421-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/617619/en-421-NotoSans-Italic.pdf)
[en-421-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/617620/en-421-NotoSansDisplay-Black.pdf)
[en-421-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/617621/en-421-NotoSansDisplay-Italic.pdf)
[en-421-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/617623/en-421-NotoSerif-Black.pdf)
[en-421-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/617622/en-421-NotoSerif-Italic.pdf)
[en-421-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/617625/en-421-NotoSerifDisplay-Black.pdf)
[en-421-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/617624/en-421-NotoSerifDisplay-Italic.pdf)

**Comment by brawer** [comment]
Two nitpicks about the HTML files for fontdiff:

* Instead of `lang="en"`, it would be better to use `lang="en-fonipa"` or `lang="und-fonipa"` (doesn’t matter which one). The former two (`en-fonipa`, `und-fonipa`) get mapped to the OpenType language system code `IPPH` for the International Phonetic Alphabet. The latter (`en`) gets mapped to language system `ENG`.

* Super-minor nitpick: `<p><span style="font-weight:700">foo</span></p>` could be simplified to `<p style="font-weight:700">foo</p>`

```html
<html lang="en">
  <p><span style="font-weight:700">d̚ g̚ d˺ g˺</span></p>
  <p><span style="font-weight:700">p̚t b̚t t̚t d̚t ʈ̚t ɖ̚t c̚t ɟ̚t k̚t ɡ̚t g̚t</span></p>
  <p><span style="font-weight:700">q̚t ɢ̚t ʡ̚t ʔ̚t m̚t ɱ̚t n̚t ɳ̚t ɲ̚t ŋ̚t ɴ̚t</span></p>
</html>
```

**Comment by brawer** [comment]
Added test cases from this bug to the existing IPA tests for Noto: https://github.com/googlei18n/noto-source/commit/6285cff1e08c0eb8c74d018ff2d03c1a743df79d

**Comment by marekjez86** [comment]
@moyogo : could you look at the test cases below and advise if placement is correct for the following tests
```html
<html lang="en-fonipa">
	<p style="font-weight:700">d̚ g̚ d˺ g˺</p>
	<p style="font-weight:700">p̚t b̚t t̚t d̚t ʈ̚t ɖ̚t c̚t ɟ̚t k̚t ɡ̚t g̚t</p>
	<p style="font-weight:700">q̚t ɢ̚t ʡ̚t ʔ̚t m̚t ɱ̚t n̚t ɳ̚t ɲ̚t ŋ̚t ɴ̚t</p>
</html>
```

samples for:
noto sans regular
![notosans-regular-421](https://cloud.githubusercontent.com/assets/13322623/21548160/8a76b27e-cd9f-11e6-916a-737138925ce2.jpeg)

noto serif regular
![notoserif-regular-421](https://cloud.githubusercontent.com/assets/13322623/21548157/7e562358-cd9f-11e6-80fb-8913f8f937c9.jpeg)

roboto regular (note that if there's a problem we'll file a bug with roboto)
![roboto-regular-421](https://cloud.githubusercontent.com/assets/13322623/21548147/71414418-cd9f-11e6-9ff3-e55cfd01ed82.jpeg)


all tests

[en-421-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677461/en-421-NotoSans-Black.pdf)
[en-421-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677458/en-421-NotoSans-Italic.pdf)
[en-421-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677457/en-421-NotoSans-Regular.pdf)
[en-421-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677460/en-421-NotoSansDisplay-Black.pdf)
[en-421-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677459/en-421-NotoSansDisplay-Italic.pdf)
[en-421-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677462/en-421-NotoSansDisplay-Regular.pdf)
[en-421-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677463/en-421-NotoSansMono-Black.pdf)
[en-421-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677465/en-421-NotoSansMono-Regular.pdf)
[en-421-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677466/en-421-NotoSerif-Black.pdf)
[en-421-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677464/en-421-NotoSerif-Italic.pdf)
[en-421-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677472/en-421-NotoSerif-Regular.pdf)
[en-421-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677471/en-421-NotoSerifDisplay-Black.pdf)
[en-421-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677468/en-421-NotoSerifDisplay-Italic.pdf)
[en-421-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677469/en-421-NotoSerifDisplay-Regular.pdf)
[en-421-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677467/en-421-Roboto-Black.pdf)
[en-421-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677470/en-421-Roboto-Italic.pdf)
[en-421-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677473/en-421-Roboto-Regular.pdf)

**Comment by marekjez86** [comment]
copying response from MTI: "This should be resolved with a layout engine that uses mark to mark placement. Kamal says each of these characters has a different function; they don’t need to look the same. I think the placement of 02FA is fine. This is not a bug."

**Comment by moyogo** [comment]
This is not resolved. There is no reason 031A should have this design. It’s clashing and it doesn’t look like this at all in any reference IPA fonts on https://www.internationalphoneticassociation.org/content/ipa-fonts or https://www.internationalphoneticassociation.org/content/full-ipa-chart.

Roboto is wrong indeed.

**Comment by nizarsq** [comment]
<img width="268" alt="Screen Shot 2020-07-22 at 1 22 00 PM" src="https://user-images.githubusercontent.com/22158882/88224780-5546a600-cc1e-11ea-891b-dd275d93b588.png">
