### ISSUE TITLE
Cousine: U+2192 and U+2194 are too low relative to Latin letters

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#439]
Moved from googlei18n/noto-alpha#240 

Imported from [Google Code issue #240](https://code.google.com/p/noto-alpha/issues/detail?id=240) created by [jungshik@google.com](https://code.google.com/u/111508351753515362661/) on 2014-06-04T22:27:36.000Z:

----
In Arimo/Tinos/Cousine, the y-position of U+2192 and U+2194 seem to be a bit too low relative to Latin letters. See the screenshot attached. 

P.S. This was reported against ChromeOS at https://code.google.com/p/chromium/issues/detail?id=247798

![screenshot_from_2014-03-13_23-59-14](https://cloud.githubusercontent.com/assets/9939212/8630990/26509514-2722-11e5-8910-a8442eb6c6cc.png)

**Comment by jungshik** [comment]
According to @dougfelt : 
This is fixed in the recent drops of Arimo v1.30 and and Tinos v1.30.  Cousine (v1.21) still has the problem.

@waksmonskiMT  : Can you fix this in Cousine as well?

**Comment by fontguy** [comment]
Probably a better comparison for these fonts is with Arial, Times, and Courier. When you do that it looks like Cousine may be properly following the low arrow heights used in Courier.

![atc](https://cloud.githubusercontent.com/assets/5133817/8969786/71218a1c-35fa-11e5-9f93-e4ff4ccb7f4a.png)

**Comment by jungshik** [comment]
Cousine is to be metric compatible with Courier New rather than Courier. And, the metric-compatibility is about the advance width. 

So, even if Courier New does the same as Courier, Cousine does not have to do the same for the vertical position of the arrow characters.

**Comment by jungshik** [comment]
@waksmonskiMT : can you update the arrow position in Cousine?  Arimo/Tinos are now fixed. Thanks

**Comment by marekjez86** [comment]
Cousine arrows are also fixed.

see 
[aCousine-TAC-all.pdf](https://github.com/googlei18n/noto-fonts/files/267089/aCousine-TAC-all.pdf)

closing bug as fixed

**Comment by segrey** [comment]
Seems it's still an issue.
Here is how Noto Sans v1.06 (https://www.google.com/get/noto/) looks in in gedit (under Linux Mint):
![image](https://cloud.githubusercontent.com/assets/607109/19889066/e3ee3950-a043-11e6-9b11-5db023a3f987.png)
