### ISSUE TITLE
Naskh Bold: Medial Feh and final Alef need adjustments to their designs

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#460]
moved from https://github.com/googlei18n/noto-alpha/issues/278

Imported from Google Code issue #278 created by roozbeh@google.com on 2015-01-15T01:32:27.000Z:

In the Naskh Bold font, two [classes of] glyphs stick out as inconsistent with the regular font, the initial form of Feh and the final form of Alef.

For the Feh, the design is very different from the regular font and appears to have a sharp corner at the bottom right side too.

For the Alef, the contrast between the bottom and the top is too much, again resulting in a appearance of it being a bit broken at the connection point to the horizontal stroke.

Note that other glyphs in the same families (initial Qaf, final Alef-Madda, etc) have the same issues as they share the outlines.

I'm attaching a sample comparing Regular and Bold. It shows the problem somehow, but the problem is much more visible when you see these in running text, such as the GMail app on Android. The initial Feh and Final Alef in the bold font really stick out there, especially in words containing both as فا.

Naskh (top) and Naskh Bold (bottom)

![024de58e-2977-11e5-8e48-d5f5cc020a00](https://cloud.githubusercontent.com/assets/13322623/9076928/202e5558-3add-11e5-8387-f6fa3b130285.png)

![024d5786-2977-11e5-8b3f-9306584394ce](https://cloud.githubusercontent.com/assets/13322623/9076941/39034f2a-3add-11e5-9349-f7ce0740b4e0.png)

**Comment by dougfelt** [comment]
MTI says this is fixed. @roozbehp can you confirm?

**Comment by marekjez86** [comment]
@roozbehp : per @dougfelt comment "MTI says this is fixed. @roozbehp can you confirm?"

**Comment by roozbehp** [comment]
Just tested. It's fixed for all characters in FEH and QAF classes. It's also fixed for most characters of the Alef class, but it's still broken for U+0773 and U+0774 (the two left-most cases):

![naskh-bold](https://cloud.githubusercontent.com/assets/302255/13336658/1a36d09a-dbcc-11e5-9f74-0b09d604a7cd.png)

I'm reducing the priority, since those two characters are used in minority languages.

**Comment by nizarsq** [comment]
As roozbehp mentioned issue still exist for U+0773 and U+0774 on current font.
<img width="1329" alt="Screen Shot 2020-06-04 at 5 24 32 PM" src="https://user-images.githubusercontent.com/22158882/83823298-8710a700-a688-11ea-9058-c49a611c500a.png">
